name: GitHub Actions
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java 
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - run: ./gradlew test
      - run: ./gradlew integTest
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/*.xml'